name: mastodon
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - expat=2.6.3
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.12.5
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - attrs==24.2.0
      - blurhash==1.1.4
      - cachetools==5.5.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - decorator==5.1.1
      - frozenlist==1.4.1
      - google-auth==2.34.0
      - google-auth-oauthlib==1.2.1
      - gspread==6.1.2
      - idna==3.10
      - mastodon-py==1.8.1
      - multidict==6.1.0
      - oauthlib==3.2.2
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - python-dateutil==2.9.0.post0
      - python-magic==0.4.27
      - pyyaml==6.0.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - six==1.16.0
      - urllib3==2.2.3
      - yarl==1.11.1
